agents:
  queue: mac
env:
  IMAGE_ID: $IMAGE_ID

# This is the default pipeline – it will build and test the app
steps:
  #################
  # Build and Test
  #################
  - label: 🧪 Build and Test
    key: test
    command: build_and_test_pod
    plugins: [$CI_TOOLKIT_PLUGIN]
    notify:
      - github_commit_status:
          context: Unit Tests

  #################
  # Validate Podspecs
  #################
  - label: 🔬 Validate Podspecs
    key: validate
    # Ideally, --allow-warnings should be removed once the warnings have been addressed
    command: validate_podspec --patch-cocoapods --allow-warnings
    plugins: [$CI_TOOLKIT_PLUGIN]
    notify:
      - github_commit_status:
          context: Validate Podspecs

  #################
  # Lint
  #################
  - label: 🧹 Lint
    key: lint
    command: lint_pod
    plugins: [$CI_TOOLKIT_PLUGIN]
    notify:
      - github_commit_status:
          context: Lint Pod

  #################
  # Publish the Podspec (if we're building a tag)
  #################
  - label: ⬆️ Publish Aztec Podspec
    key: publish-aztec
    command: .buildkite/publish-aztec-pod.sh
    plugins: [$CI_TOOLKIT_PLUGIN]
    depends_on:
      - test
      - validate
      - lint
    if: build.tag != null
    notify:
      - github_commit_status:
          context: Publish Aztec Podspec

  #################
  # Publish the Podspec (if we're building a tag)
  #################
  - label: ⬆️ Publish Editor Podspec
    key: publish-editor
    command: .buildkite/publish-editor-pod.sh
    plugins: [$CI_TOOLKIT_PLUGIN]
    depends_on:
      - test
      - validate
      - lint
    if: build.tag != null
    notify:
      - github_commit_status:
          context: Publish WordPress-Editor Podspec
